name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Restore
      run: dotnet restore
    - name: Build
      run: |
        dotnet publish src/reeutils -c Release -o out/reeutils --os linux
        dotnet publish src/reeutils -c Release -o out/reeutils --os win
    - name: Pack
      run: |
        cd out/reeutils
        rm -rf *.deps.json *.pdb de fr sv
        cp ../../script/* .
        cd ..
        tar czf ../reeutils.tar.gz .
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: reeutils
        path: out/**/*
    - name: Create release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        fail_on_unmatched_files: true
        files: reeutils.tar.gz
